version: "3.8"

services:
    mysql:
        container_name: Database_Portfolio
        image: mysql:latest
        volumes:
            - 'apache-mysql:/var/lib/mysql'
        ports:
            - '${FORWARDED_DB_PORT:-3306}:3306'
        environment:
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        networks:
            - portfolionetwork


  php-apache:
    container_name: Portfolio_Appplication
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${APP_PORT:-80}:80'
    volumes:
      - '.:/var/www/html/'
    networks:
      - portfolionetwork
    depends_on:
      - mysql

  composer:
    container_name: Composer_Portfolio
    image: composer:latest
    volumes:
      - '.:/app'
    command: >
        bash -c "composer install
        && composer update"
networks:
  portfolionetwork:
    driver: bridge

volumes:
  apache-mysql:
    driver: local
